const email = document.querySelector('.enter-mail')
const password = document.querySelector('.enter-password')
const signInBtn = document.querySelector('.sign-in-btn')
const signWithCode = document.querySelector('.sign-in-with-code-btn')
const forgotPassword = document.querySelector('.forgot-pswrd-btn')
const rememberMeButton = document.querySelector('.remember-me-btn')